//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONSTRUCTION.DataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Date { get; set; }
        public string Image { get; set; }
        public string BlogTitle { get; set; }
        public string ShortDescription { get; set; }
        public string Blogdetail { get; set; }
        public string URL { get; set; }
        public string MetaTags { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string SEOTitle { get; set; }
        public string SEODescription { get; set; }
        public Nullable<bool> IsCrawl { get; set; }
    }
}
