//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONSTRUCTION.DataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAddCityTechMaster
    {
        public int Id { get; set; }
        public Nullable<int> TechMasterId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string FocusKeyphrase { get; set; }
        public string SEOtitle { get; set; }
        public string Slug { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<bool> IsCrawl { get; set; }
        public string CanonicalURL { get; set; }
        public string SchemaTags { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string BriefDescription { get; set; }
    }
}
