//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONSTRUCTION.DataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRefer
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string FriendFullName { get; set; }
        public string FriendEmail { get; set; }
        public string FriendPhoneNo { get; set; }
        public string Description { get; set; }
        public Nullable<int> JobId { get; set; }
    }
}
